version: '3.8'

services:
  app:
    build: .
    container_name: nestjs-app
    ports:
      - '3333:3333'
      - '9229:9229'
    env_file: .env
    working_dir: /home/node/app
    depends_on:
      db:
        condition: service_healthy
      keycloak:
        condition: service_healthy
    volumes:
      - ./:/home/node/app

  db:
    container_name: postgres
    image: postgres
    ports:
      - 5432:5432
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: docker
      POSTGRES_DB: main
      PGDATA: /data/postgres
    volumes:
      - ./data/pg:/data/postgres
      - ./scripts/init.sql:/docker-entrypoint-initdb.d/init.sql
    healthcheck:
      test: ['CMD-SHELL', 'pg_isready -U postgres']
      interval: 5s
      timeout: 5s
      retries: 5

  keycloak:
    container_name: keycloak
    image: bitnami/keycloak:22.0.5
    ports:
      - 8080:8080
    volumes:
      - ./data/keycloak:/home/node/app/data/keycloak
      - ./scripts/realm-export.json:/opt/bitnami/keycloak/data/import/realm-export.json
    depends_on:
      db:
        condition: service_healthy
    environment:
      KEYCLOAK_ADMIN_USER: admin
      KEYCLOAK_ADMIN_PASSWORD: admin
      KC_HTTP_RELATIVE_PATH: '/auth/'
      KC_DB: postgres
      KC_DB_URL: 'jdbc:postgresql://db/keycloak'
      KC_DB_USERNAME: postgres
      KC_DB_PASSWORD: docker
      KEYCLOAK_DATABASE_VENDOR: postgres
      KEYCLOAK_EXTRA_ARGS: '--import-realm'
    healthcheck:
      test: curl --fail http://keycloak:8080/auth || exit 1
      interval: 5s
      timeout: 15s
      retries: 5
