export const KNC_INSTANCE = 'KNC_INSTANCE';
export const KNC_OPTIONS = 'KNC_OPTIONS';
export const KNC_LOGIN = 'KNC_LOGIN';
export const KNC_SKIP_AUTH = 'KNC_SKIP_AUTH';
export const KNC_AUTHORIZED_CLIENTS = 'KNC_AUTHORIZED_CLIENTS';
